### ISSUE TITLE
Prepare for Ruby version 3

### ISSUE THREAD

**Issue by LeamHall** [edgecase/ruby_koans#20]
A few of the koans test for the ruby version, and do not allow for "3". 
Working on a PR now.

**Comment by Krap** [comment]
Was about to submit the same PR. Is the project dead ?

**Comment by LeamHall** [comment]
> Was about to submit the same PR. Is the project dead ?

It seems so. I have moved away from Ruby, but the koans were fun to build my learning.

**Comment by aedwardg** [comment]
Until #21 is merged, for anyone who wants to pass `AboutMessagePassing#test_calling_method_missing_causes_the_no_method_error` (at 92% complete) with Ruby 3 and _not_ have to wipe out your progress with `rake regen`, make sure you make the change seen [here](https://github.com/edgecase/ruby_koans/pull/21/files#diff-e24c3ed0770fd0b847ae00dfb01a50a0c8efe7c4a4db77abeb4855afc3994e4eR73) except you'll need to do it in `/koans/neo.rb` rather than `/src/neo.rb`.  

Once the koans have been generated, they include the version at `/koans/neo.rb` so the two options are to update that file directly or regenerate the koans and lose all your progress 😅

**Comment by lalaithan** [comment]
> Is the project dead ?

From the http://rubykoans.com/ website: The Ruby Koans were principally the work of Jim Weirich while working at EdgeCase. Jim sadly passed away in 2014.

**Comment by LeamHall** [comment]
You can fork the project and build your own improvements into it. Of course, that requires understanding Ruby. When I looked at the actual code for this, it really isn't that difficult. Is that something you'd want to do?

**Comment by lalaithan** [comment]
No, the website claims anything above 1.8 is fine and I don't have the spare time to do a completely updated fork of this repo. I merely posted this for anyone passing by wondering why this was not too actively updated.

**Comment by tonywok** [comment]
Hey friends, I've modified my notifications to make sure I see issues such as this going forward.

Doing some housecleaning and triaging some issues/PRs and then remembering how deployment works 😅

The koans live on! Thanks for your interest and contribution!

**Comment by tonywok** [comment]
I'm going to close these as #28 was merged. Updating the zip in a few :)

Let me know if you see any other ruby 3 related issues. I'm going to see if I have time to beef up our testing a bit. Would be nice to run against latest stable ruby.
