### ISSUE TITLE
rubykoans.com 502

### ISSUE THREAD

**Issue by pjfitzgibbons** [edgecase/ruby_koans#41]
Website has gone 502!

Oh Noez.

If this requires patching, assistance, motivation, encouragement, enlightenment, whatever, ...

Ping me.

@pjfitzgibbons

**Comment by lbvf50mobile** [comment]
Greetings.

At  the https://www.rubykoans.com/ was a strange "HELLO DASH" dashboard before 502 appears.

Ruby Koans is a real treasure of Ruby Community, best way to get into Ruby development in a short time. This issue is outstanding important.

Thank you.



 

![ruby_koans_dash_502](https://user-images.githubusercontent.com/23147487/234483250-a988fd43-9202-4953-8965-a0b1639dc3b7.png)

**Comment by pjfitzgibbons** [comment]
Site has been restored.

Closing this.

**Comment by lbvf50mobile** [comment]
Again https://www.rubykoans.com/ is not accessible. Now request for authorization Username/Password.

**Comment by lbvf50mobile** [comment]
https://github.com/ruby/www.ruby-lang.org/pull/3050 - created PR to substitute unstable rubykoans.com by this repo.
 
![auth_required](https://user-images.githubusercontent.com/23147487/234976445-198c15d1-5332-4eee-b4c6-f0daeca33ceb.png)
![auth_required1](https://user-images.githubusercontent.com/23147487/234976460-e7119ff2-ad56-406e-a363-a06d110f4297.png)
